name: Delete old workflow runs
on:
  workflow_dispatch: # 允许手动点击运行

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0 # 保留0天（即删除所有旧记录）
          keep_minimum_runs: 0 # 不保留任何记录
