name: Update EPG

on:
  schedule:
    # 每天美东时间早上 01:12 运行 (UTC 05:12)
    - cron: '12 5 * * *'
  workflow_dispatch: # 允许手动点击按钮触发

# 添加这个全局环境变量，强制 Actions 使用 Node.js 24，从而消除警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests
      - name: Run EPG Script
        run: |
          python epg_offset.py
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add slim_fixed_epg.xml
          git commit -m "Auto update EPG" || exit 0
          git push
